Fix "undefined method 'stubs'" by requiring mocha/api
Currently trying to create a MockFunction using the `stub` or `stubbed`
methods returns a NoMethodError:
```
irb(main):002:0> require 'rspec'
=> true
irb(main):003:0> require 'rspec-puppet-utils'
=> true
irb(main):004:0> MockFunction.new('query_nodes') { |f| f.stubbed.returns([]) }
NoMethodError: undefined method `stubs' for #<RSpecPuppetUtils::MockFunction:0x007f954445f390>
        from /Users/mattcasper/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/rspec-puppet-utils-2.2.1/lib/mock_function.rb:32:in `stubbed'
        from (irb):4:in `block in irb_binding'
        from /Users/mattcasper/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/rspec-puppet-utils-2.2.1/lib/mock_function.rb:20:in `initialize'
        from (irb):4:in `new'
        from (irb):4
        from /Users/mattcasper/.rbenv/versions/2.1.9/bin/irb:11:in `<main>'
```

This is because you need to require 'mocha/api' to get the `stubs`
method, not just 'mocha'.

In this library's tests (and probably most people's tests) this is
avoided because `puppetlabs_spec_helper` sets up `mocha` as well:
https://github.com/puppetlabs/puppetlabs_spec_helper/blob/master/lib/puppetlabs_spec_helper/puppet_spec_helper.rb#L11
https://github.com/puppetlabs/puppetlabs_spec_helper/blob/master/lib/puppetlabs_spec_helper/puppet_spec_helper.rb#L122

But just on its own, this errors out.