add missing dependency on thor for fedora
resolves TB on Fedora 20:

    $ bundle exec rake -T
    rake aborted!
    LoadError: cannot load such file -- thor
    /usr/share/gems/gems/bundler-1.7.3/lib/bundler/vendored_thor.rb:7:in `require'
    /usr/share/gems/gems/bundler-1.7.3/lib/bundler/vendored_thor.rb:7:in `<top (required)>'
    /usr/share/gems/gems/bundler-1.7.3/lib/bundler/gem_helper.rb:1:in `require'
    /usr/share/gems/gems/bundler-1.7.3/lib/bundler/gem_helper.rb:1:in `<top (required)>'
    /usr/share/gems/gems/bundler-1.7.3/lib/bundler/gem_tasks.rb:1:in `require'
    /usr/share/gems/gems/bundler-1.7.3/lib/bundler/gem_tasks.rb:1:in `<top (required)>'
    /home/user/rspec-puppet-utils/Rakefile:1:in `require'
    /home/user/rspec-puppet-utils/Rakefile:1:in `<top (required)>'
    (See full trace by running task with --trace)